---
- name: Add mongodb repository
  apt_repository:
    repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse
    state: present

- name: Install mongodb key
  apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
    state: present

- name: Update cache
  apt:
    update_cache: yes

- name: Install mongodb
  apt:
    name: mongodb-org

- name: Start mongod
  command: service mongod start