---
   - name: Include encrypted variables
     include_vars: "encrypted.yml"

   - name: Allow inbound access
     iptables:
       action: insert
       chain: INPUT
       protocol: tcp
       destination_port: "{{ item }}"
       jump: ACCEPT
       state: present
     with_items:
       - 5672
       - 5432
