---
   - name: Check if known_hosts exists
     stat:
       path: "{{ app_home }}/.ssh/known_hosts"
     register: known_hosts

   - name: Clean known_hosts from github.com public key
     command: 'ssh-keygen -R github.com'
     become: yes
     become_user: "{{ app_user }}"
     when: known_hosts.stat.exists == True

   - name: Authenticate at repo
     command: "/var/tmp/authgithub"
     args:
       chdir: "{{ app_home }}"
     become: yes
     become_user: "{{ app_user }}"

   - name: Clone repo
     command: "/usr/bin/git clone git@github.com:lspliner/ravop-plugins.git {{ app_home }}/ravop-plugins"
     become: yes
     become_user: "{{ app_user }}"
  