---
   - name: Configure service
     template:
       src: "serevice.j2"
       dest: "/etc/systemd/system/{{ unit_name }}.service"

   - name: Enable service
     command: "{{ item }}"
     with_items:
       - systemctl daemon-reload
       - "systemctl enable {{ unit_name }}.service"