---
   - name: Download erlang
     get_url:
       url: http://packages.erlang-solutions.com/site/esl/esl-erlang/FLAVOUR_1_general/esl-erlang_20.1-1~ubuntu~xenial_amd64.deb
       dest: /var/tmp/erlang-20.1-amd64.deb

   - name: Download rabbit
     get_url:
       url:  https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.7.3/rabbitmq-server_3.7.3-1_all.deb
       dest: /var/tmp/rabbitmq-server-3.7.3-all.deb

   - name: Install custom packages
     command: "{{ item }}"
     with_items:
     - apt install -y /var/tmp/erlang-20.1-amd64.deb
     - apt install -y /var/tmp/rabbitmq-server-3.7.3-all.deb

   - name: Enable rabbit management
     rabbitmq_plugin:
       state: enabled
       names: rabbitmq_management

# todo: add administrator and disable guest/guest administration